name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.22.x"
          - "1.23.x"
          - "1.24.x"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run tests
        run: ./ci/test.sh
